name: openmmlab5
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pillow=10.4.0
  - pip=24.2
  - pysocks=1.7.1
  - python=3.8.20
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - sqlite=3.45.3
  - sympy=1.13.2
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.0.0
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - typing_extensions=4.11.0
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - cffi==1.17.1
      - colorama==0.4.6
      - crcmod==1.7
      - cryptography==44.0.0
      - filelock==3.14.0
      - importlib-metadata==8.5.0
      - jmespath==0.10.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mmcv==2.0.1
      - mmdet==3.3.0
      - mmengine==0.10.5
      - model-index==0.1.11
      - opencv-python==4.10.0.84
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - platformdirs==4.3.6
      - prettytable==3.11.0
      - protobuf==5.29.2
      - psutil==6.1.1
      - pycocotools==2.0.7
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pygments==2.18.0
      - pyyaml==6.0.2
      - requests==2.28.2
      - rich==13.4.2
      - setuptools==60.2.0
      - shapely==2.0.6
      - six==1.17.0
      - tabulate==0.9.0
      - terminaltables==3.1.10
      - tomli==2.2.1
      - tqdm==4.65.2
      - urllib3==1.26.20
      - yapf==0.43.0
      - zipp==3.20.2
